- name: Configure Node VM
  hosts: azure
  user: master
  become: yes

  vars:
    myResourceGroup: Devops
    myVM: ansible-node

  tasks:
  
  - name: Install Various Packages
    apt:
      update_cache: yes
      name: "{{ packages }}"
    vars:
      packages:
      - libssl-dev
      - libffi-dev
      - python-dev
      - python-pip

  - name: Install Ansible for Azure
    command: pip install ansible[azure]
    
  - stat:
      path: /home/master/docker_node.sh
    register: result

  - name: Copy docker_node.sh to Node
    copy:
      src: ./docker_node.sh
      dest: /home/master/docker_node.sh
      when: result.stat.exists == false
    
  - name: Set docker.sh permissions
    command: chmod +x /home/master/docker_node.sh

  - name: Run Docker installation script
    command: sudo /home/master/docker_node.sh

